# Simple workflow for deploying static content to GitHub Pages
name: Build and Test Pyrefly Website
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Allow this workflow to be called by other workflows
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
    types: [opened]
    paths:
      - 'website/**'

jobs:
  # Single deploy job since we're just deploying
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install yarn deps
        run: cd website && yarn install
      - name: Install wasm-pack
        run: cargo install wasm-pack wasm-opt
      - name: Use rust nightly
        run: rustup install nightly && rustup default nightly
      - name: Build
        working-directory: ./website
        run: cargo version && chmod +x scripts/build.sh && scripts/build.sh && yarn build-wasm-for-test
      - name: Typecheck
        working-directory: ./website
        run: yarn tsc --noEmit
      - name: Test
        working-directory: ./website
        run: yarn test
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website-build-${{ env.date }}
          path: website/build
          retention-days: 30
