name: deploy_extension
on:
  push:
    paths:
      - version.bzl
    branches: [ main ]
  workflow_dispatch:

jobs:
    build:
        uses: ./.github/workflows/build_extension.yml

    test:
        uses: ./.github/workflows/pyrefly.yml

    publish_code_marketplace:
        runs-on: ubuntu-latest
        needs:
          - build
          - test
        if: success()
        steps:
            - name: upload
              uses: actions/download-artifact@v4
            - name: publish
              run: npx vsce publish --packagePath $(find . -iname *.vsix)
              env:
                VSCE_PAT: ${{ secrets.VSCE_PAT }}

    publish_openvsx:
        runs-on: ubuntu-latest
        needs:
          - build
          - test
        if: success()
        steps:
            - name: upload
              uses: actions/download-artifact@v4
            - name: publish
              run: npx ovsx publish --packagePath $(find . -iname *.vsix) --pat ${{ secrets.OPENVSX_TOKEN }}
